version: "3.8"

services:
    web:
        image: upsight:1.0
        build: .
        restart: always
        command: gunicorn miniintern.wsgi:application --bind 0.0.0.0:8000
        depends_on:
            db:
                condition: service_healthy # DB가 완전히 시작될 때까지 기다림
        ports:
            - "8000:8000"
        env_file:
            - .env
        volumes:
            - .:/code

    db:
        image: postgres:14
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    postgres_data:
