version: "3.8"

services:
    web:
        image: upsight:1.0
        build: .
        restart: always
        command: gunicorn miniintern.wsgi:application --bind 0.0.0.0:8000
        depends_on:
            db:
                condition: service_healthy
        ports:
            - "8000:8000"
        env_file:
            - .env
        volumes:
            - .:/code

    db:
        image: postgres:14
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
            - postgres_data:/var/lib/postgresql/data/
            - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    'pg_isready -U ${POSTGRES_USER} && psql -U ${POSTGRES_USER} -d postgres -tAc "SELECT 1 FROM pg_database WHERE datname=''${POSTGRES_DB}''" | grep -q 1',
                ]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    postgres_data:
