version: "3.8"

services:
    web:
        image: upsight:1.0
        build: .
        command: gunicorn miniintern.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        env_file:
            - .env
        depends_on:
            - db

    db:
        image: postgres:14
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
    postgres_data:
