# Generated by Django 4.2 on 2024-10-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmember',
            name='role',
            field=models.CharField(choices=[('admin', 'Business Admin'), ('member', 'Business Member')], default='member', max_length=20),
        ),
    ]
