# Generated by Django 5.1.1 on 2024-10-21 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('boards', '0003_remove_comment_is_deleted_remove_post_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessmember',
            name='business',
        ),
        migrations.AlterField(
            model_name='post',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='authentication.business'),
        ),
        migrations.RemoveField(
            model_name='businessmember',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='businessmember',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.DeleteModel(
            name='BusinessMember',
        ),
    ]
